search-dir: ".\\"
# May be the full file name a portion of it
# wildcards (*) or other regex are not supported at this time
spreadsheet-pattern: "db-output" 
# column modifications
# can merge or just rename by including only one old-column
# the new column name must not exist already
# the columns are joined in the order listed
# and separated by the specified seperator
modify-columns:
- new-name: Name
  old-columns: 
    - "[Child] First Name"
    - "[Child] Last Name"
  seperator: " "
- new-name: Contact
  old-columns: 
    - "[Parent] First Name"
    - "[Parent] Last Name"
  seperator: " "
- new-name: Contact Number
  old-columns: 
    - "[Parent] Phone"
  seperator: " "
# optional
# if provided, the value in this column (which should be the same for all rows)
# will be printed under the title as is (unless date-format is specified)
date-column: Session Date
# optional
# formats the date-column data
# example: "%m/%d/%y %H:%M:%S"
# see: https://docs.python.org/3.13/library/datetime.html#strftime-and-strptime-format-codes
date-format: "%m/%d/%y"
# a list of columns to print in the order they should be printed
# the columns must be in the orignnal spreadsheet
# OR the new column names from the modify-columns list
columns-to-print: 
- Name
- Contact
- Contact Number
# Prints one sheet per unique value in the below column
# does not need to be in the columns list
class-column-name: Session
# appended to the contents of the class column name 
title-suffix: "Roster"
# optional
# Either 'P' for portrait or 'L' for landscape
# if not specified, defaults to portrait
orientation: P
# optional
# adds the print time to the footer
# default is false
show-print-date: True
# optional
# adds the spreadsheet modiefied time to the footer
# default is false
show-modified-time: True
# optional