search-dir: ".\\"
# May be the full file name a portion of it
# wildcards (*) or other regex are not supported at this time
spreadsheet-pattern: "check-ins" 
# column modifications
# can merge or just rename by including only one old-column
# the new column name must not exist already 
modify-columns:
- new-name: Name
  old-columns: 
    - "First Name"
    - "Last Name"
- new-name: Contact
  old-columns: 
    - "Parent First Name"
    - "Parent Last Name"
- new-name: Contact Number
  old-columns: 
    - "Parent Phone"
# a list of columns to print in the order they should be printed
# the columns must be in the orignnal spreadsheet
# OR the new column names from the modify-columns list
columns-to-print: 
- Name
- Security Code
- Contact
- Contact Number
# Prints one sheet per unique value in the below column
# does not need to be in the columns list
class-column-name: Session
# appended to the contents of the class column name 
title-suffix: "Roster"